# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='image',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='type_cif',
        ),
        migrations.AlterField(
            model_name='institution',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pays',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='where',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='cat_assistance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='cat_fonctions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='cat_techno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='mobility',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='type_age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='type_environnement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
